dontChroot: false
timeout: 900
script:
  - "flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo"
  - "sudo apt install gnome-software-plugin-flatpak"
  - "sudo rm -rf /usr/share/HackerOS/Scripts/calamares.sh && sudo rm -rf /usr/share/HackerOS/Scripts/update-files.sh && sudo rm -rf /etc/xdg/autostart/calamares.desktop && sudo rm -rf /etc/xdg/autostart/update-files.desktop"
